
dataset: weibo_en
root_path: /media/shared_d/lyq/DataSet/FakeNews/weibo_en
batch_size: 128
ModelConfig:
  cache_file_path: 'deepseek671B_pred.pkl'
  save_file_path: 'deepseek671B_pred.csv'
  bootConfig:
    # url: 'https://api.siliconflow.cn/v1'
    url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
    api_key: 'api_key'
    model_name: 'deepseek-r1-distill-llama-70b'
  generateConfig:
    temperature: 0.7
    top_p: 0.8
    repetition_penalty: 1.00
