
dataset: weibo
qwen_path: /home/lyq/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4
root_path: /media/shared_d/lyq/DataSet/FakeNews/weibo_dataset
batch_size: 1
rationale_name: img
few_shot:
  enable: true
  num_few_shot: 4
  few_shot_dir: /media/shared_d/lyq/DataSet/FakeNews/LLMFND_few_shot
QwenConfig:
  RemoteConfig:
   base_url: 'http://localhost:8000/v1/'
   model_name: '/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4/'
  # LocalConfig:
  #   gpu_memory_utilization: 0.9
  #   tensor_parallel_size: 4
  generateConfig:
    temperature: 0.7
    top_p: 0.8
    repetition_penalty: 1.05
    max_tokens: 256