
dataset: gossipcop
qwen_path: /home/lyq/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4
root_path: /home/lyq/DataSet/FakeNews/gossipcop
batch_size: 64
rationale_name: itc
few_shot:
  enable: false
  num_few_shot: 4
  few_shot_dir: /home/lyq/DataSet/FakeNews/LLMFND_few_shot
QwenConfig:
  bootConfig:
    gpu_memory_utilization: 0.8
    tensor_parallel_size: 2
  generateConfig:
    temperature: 0.7
    top_p: 0.8
    repetition_penalty: 1.05
    max_tokens: 256