
dataset: gossipcop
qwen_path: /home/lyq/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4
root_path: /home/lyq/DataSet/FakeNews/gossipcop
batch_size: 16
QwenConfig:
  gpu_memory_utilization: 0.8
  tensor_parallel_size: 4
  #temperature: 0.7
  #top_p: 0.8
  #repetition_penalty: 1.05
  #max_tokens: 256