
dataset: weibo
qwen_path: /home/lyq/Model/Qwen2.5-72B-Instruct-GPTQ-Int8
root_path: /home/lyq/DataSet/FakeNews/weibo_dataset
batch_size: 1
rationale_name: td
few_shot:
  enable: true
  num_few_shot: 4
  few_shot_dir: /home/lyq/DataSet/FakeNews/LLMFND_few_shot