
dataset: gossipcop
qwen_path: /home/lyq/Model/Qwen2.5-72B-Instruct-GPTQ-Int8
root_path: /home/lyq/DataSet/FakeNews/gossipcop
batch_size: 256
QwenConfig:
  bootConfig:
    gpu_memory_utilization: 0.8
    tensor_parallel_size: 2
  generateConfig:
    temperature: 0.7
    top_p: 0.8
    repetition_penalty: 1.00
    max_tokens: 256